; Song ids are calculated by address to save space.

;music_const: MACRO
;\1 EQUS "RB(\2)"
;ENDM
const_value = 1

    const MUSIC_PALLET_TOWN
	const MUSIC_POKECENTER
	const MUSIC_GYM
	const MUSIC_CITIES1
	const MUSIC_CITIES2
	const MUSIC_CELADON
	const MUSIC_CINNABAR
	const MUSIC_VERMILION
	const MUSIC_LAVENDER
	const MUSIC_SS_ANNE
	const MUSIC_MEET_PROF_OAK
	const MUSIC_MEET_RIVAL
	const MUSIC_MUSEUM_GUY
	const MUSIC_SAFARI_ZONE
	const MUSIC_PKMN_HEALED
	const MUSIC_ROUTES1
	const MUSIC_ROUTES2
	const MUSIC_ROUTES3
	const MUSIC_ROUTES4
	const MUSIC_INDIGO_PLATEAU
	
	const MUSIC_GYM_LEADER_BATTLE
	const MUSIC_TRAINER_BATTLE
	const MUSIC_WILD_BATTLE
	const MUSIC_FINAL_BATTLE
	const MUSIC_DEFEATED_TRAINER
	const MUSIC_DEFEATED_WILD_MON
	const MUSIC_DEFEATED_GYM_LEADER
	
	const MUSIC_TITLE_SCREEN
	const MUSIC_CREDITS
	const MUSIC_HALL_OF_FAME
	const MUSIC_OAKS_LAB
	const MUSIC_JIGGLYPUFF_SONG
	const MUSIC_BIKE_RIDING
	const MUSIC_SURFING
	const MUSIC_GAME_CORNER
	const MUSIC_INTRO_BATTLE
	const MUSIC_DUNGEON1
	const MUSIC_DUNGEON2
	const MUSIC_DUNGEON3
	const MUSIC_CINNABAR_MANSION
	const MUSIC_POKEMON_TOWER
	const MUSIC_SILPH_CO
	const MUSIC_MEET_EVIL_TRAINER
	const MUSIC_MEET_FEMALE_TRAINER
	const MUSIC_MEET_MALE_TRAINER

	const SFX_NOISE_INSTRUMENT01
	const SFX_NOISE_INSTRUMENT02
	const SFX_NOISE_INSTRUMENT03
	const SFX_NOISE_INSTRUMENT04
	const SFX_NOISE_INSTRUMENT05
	const SFX_NOISE_INSTRUMENT06
	const SFX_NOISE_INSTRUMENT07
	const SFX_NOISE_INSTRUMENT08
	const SFX_NOISE_INSTRUMENT09
	const SFX_NOISE_INSTRUMENT10
	const SFX_NOISE_INSTRUMENT11
	const SFX_NOISE_INSTRUMENT12
	const SFX_NOISE_INSTRUMENT13
	const SFX_NOISE_INSTRUMENT14
	const SFX_NOISE_INSTRUMENT15
	const SFX_NOISE_INSTRUMENT16
	const SFX_NOISE_INSTRUMENT17
	const SFX_NOISE_INSTRUMENT18
	const SFX_NOISE_INSTRUMENT19
	
NOISE_INSTRUMENTS_START EQUS "SFX_NOISE_INSTRUMENT01"
NOISE_INSTRUMENTS_END EQUS "SFX_NOISE_INSTRUMENT19 + 1"
	
	const SFX_CRY_00
	const SFX_CRY_01
	const SFX_CRY_02
	const SFX_CRY_03
	const SFX_CRY_04
	const SFX_CRY_05
	const SFX_CRY_06
	const SFX_CRY_07
	const SFX_CRY_08
	const SFX_CRY_09
	const SFX_CRY_0A
	const SFX_CRY_0B
	const SFX_CRY_0C
	const SFX_CRY_0D
	const SFX_CRY_0E
	const SFX_CRY_0F
	const SFX_CRY_10
	const SFX_CRY_11
	const SFX_CRY_12
	const SFX_CRY_13
	const SFX_CRY_14
	const SFX_CRY_15
	const SFX_CRY_16
	const SFX_CRY_17
	const SFX_CRY_18
	const SFX_CRY_19
	const SFX_CRY_1A
	const SFX_CRY_1B
	const SFX_CRY_1C
	const SFX_CRY_1D
	const SFX_CRY_1E
	const SFX_CRY_1F
	const SFX_CRY_20
	const SFX_CRY_21
	const SFX_CRY_22
	const SFX_CRY_23
	const SFX_CRY_24
	const SFX_CRY_25

CRY_SFX_START EQUS "SFX_CRY_00"
CRY_SFX_END EQUS "SFX_CRY_25 + 3"

	const SFX_GET_ITEM_2
	const SFX_TINK
	const SFX_HEAL_HP
	const SFX_HEAL_AILMENT
	const SFX_START_MENU
	const SFX_PRESS_AB

	const SFX_GET_ITEM_1

	const SFX_POKEDEX_RATING
	const SFX_GET_KEY_ITEM
	const SFX_POISONED
	const SFX_TRADE_MACHINE
	const SFX_TURN_ON_PC
	const SFX_TURN_OFF_PC
	const SFX_ENTER_PC
	const SFX_SHRINK
	const SFX_SWITCH
	const SFX_HEALING_MACHINE
	const SFX_TELEPORT_EXIT_1
	const SFX_TELEPORT_ENTER_1
	const SFX_TELEPORT_EXIT_2
	const SFX_LEDGE
	const SFX_TELEPORT_ENTER_2
	const SFX_FLY
	const SFX_DENIED
	const SFX_ARROW_TILES
	const SFX_PUSH_BOULDER
	const SFX_SS_ANNE_HORN
	const SFX_WITHDRAW_DEPOSIT
	const SFX_CUT
	const SFX_GO_INSIDE
	const SFX_SWAP
	const SFX_59
	const SFX_PURCHASE
	const SFX_COLLISION
	const SFX_GO_OUTSIDE
	const SFX_SAVE

	const SFX_POKEFLUTE
	const SFX_SAFARI_ZONE_PA

MAX_SFX_ID_1 EQUS "SFX_SAFARI_ZONE_PA"

	const SFX_LEVEL_UP

	const SFX_BALL_TOSS
	const SFX_BALL_POOF
	const SFX_FAINT_THUD
	const SFX_RUN
	const SFX_DEX_PAGE_ADDED
	const SFX_CAUGHT_MON

	const SFX_PECK
	const SFX_FAINT_FALL
	const SFX_BATTLE_09
	const SFX_POUND
	const SFX_BATTLE_0B
	const SFX_BATTLE_0C
	const SFX_BATTLE_0D
	const SFX_BATTLE_0E
	const SFX_BATTLE_0F
	const SFX_DAMAGE
	const SFX_NOT_VERY_EFFECTIVE
	const SFX_BATTLE_12
	const SFX_BATTLE_13
	const SFX_BATTLE_14
	const SFX_VINE_WHIP
	const SFX_BATTLE_16
	const SFX_BATTLE_17
	const SFX_BATTLE_18
	const SFX_BATTLE_19
	const SFX_SUPER_EFFECTIVE
	const SFX_BATTLE_1B
	const SFX_BATTLE_1C
	const SFX_DOUBLESLAP
	const SFX_BATTLE_1E
	const SFX_HORN_DRILL
	const SFX_BATTLE_20
	const SFX_BATTLE_21
	const SFX_BATTLE_22
	const SFX_BATTLE_23
	const SFX_BATTLE_24
	const SFX_BATTLE_25
	const SFX_BATTLE_26
	const SFX_BATTLE_27
	const SFX_BATTLE_28
	const SFX_BATTLE_29
	const SFX_BATTLE_2A
	const SFX_BATTLE_2B
	const SFX_BATTLE_2C
	const SFX_PSYBEAM
	const SFX_BATTLE_2E
	const SFX_BATTLE_2F
	const SFX_PSYCHIC_M
	const SFX_BATTLE_31
	const SFX_BATTLE_32
	const SFX_BATTLE_33
	const SFX_BATTLE_34
	const SFX_BATTLE_35
	const SFX_BATTLE_36
	const SFX_SILPH_SCOPE

BATTLE_SFX_START EQUS "SFX_PECK"
BATTLE_SFX_END   EQUS "SFX_SILPH_SCOPE + 1"
MAX_SFX_ID_2 EQUS "SFX_SILPH_SCOPE"

	const SFX_INTRO_LUNGE
	const SFX_INTRO_HIP
	const SFX_INTRO_HOP
	const SFX_INTRO_RAISE
	const SFX_INTRO_CRASH
	const SFX_INTRO_WHOOSH
	const SFX_SLOTS_STOP_WHEEL
	const SFX_SLOTS_REWARD
	const SFX_SLOTS_NEW_SPIN
	const SFX_SHOOTING_STAR

MAX_SFX_ID_3 EQUS "SFX_SHOOTING_STAR"

SFX_STOP_ALL_MUSIC EQU $ff

; mappings

const_value = 1

	const RBSFX_02_3a
	const RBSFX_02_3b
	const RBSFX_02_3c
	const RBSFX_02_3d
	const RBSFX_02_3e
	const RBSFX_02_3f
	const RBSFX_02_40
	const RBSFX_02_41
	const RBSFX_02_42
	const RBSFX_02_43
	const RBSFX_02_44
	const RBSFX_02_45
	const RBSFX_02_46
	const RBSFX_02_47
	const RBSFX_02_48
	const RBSFX_02_49
	const RBSFX_02_4a
	const RBSFX_02_4b
	const RBSFX_02_4c
	const RBSFX_02_4d
	const RBSFX_02_4e
	const RBSFX_02_4f
	const RBSFX_02_50
	const RBSFX_02_51
	const RBSFX_02_52
	const RBSFX_02_53
	const RBSFX_02_54
	const RBSFX_02_55
	const RBSFX_02_56
	const RBSFX_02_57
	const RBSFX_02_58
	const RBSFX_02_59
	const RBSFX_02_5a
	const RBSFX_02_5b
	const RBSFX_02_5c
	const RBSFX_02_5d
	const RBSFX_02_5e
	const RBSFX_02_5f

	const RBSFX_08_41
	const RBSFX_08_42
	const RBSFX_08_43
	const RBSFX_08_44
	const RBSFX_08_45
	const RBSFX_08_46
	const RBSFX_08_47
	const RBSFX_08_48
	const RBSFX_08_49
	const RBSFX_08_4a
	const RBSFX_08_4b
	const RBSFX_08_4c
	const RBSFX_08_4d
	const RBSFX_08_4e
	const RBSFX_08_4f
	const RBSFX_08_50
	const RBSFX_08_51
	const RBSFX_08_52
	const RBSFX_08_53
	const RBSFX_08_54
	const RBSFX_08_55
	const RBSFX_08_56
	const RBSFX_08_57
	const RBSFX_08_58
	const RBSFX_08_59
	const RBSFX_08_5a
	const RBSFX_08_5b
	const RBSFX_08_5c
	const RBSFX_08_5d
	const RBSFX_08_5e
	const RBSFX_08_5f
	const RBSFX_08_60
	const RBSFX_08_61
	const RBSFX_08_62
	const RBSFX_08_63
	const RBSFX_08_64
	const RBSFX_08_65
	const RBSFX_08_66
	const RBSFX_08_67
	const RBSFX_08_68
	const RBSFX_08_69
	const RBSFX_08_6a
	const RBSFX_08_6b
	const RBSFX_08_6c
	const RBSFX_08_6d
	const RBSFX_08_6e
	const RBSFX_08_6f
	const RBSFX_08_70
	const RBSFX_08_71
	const RBSFX_08_72
	const RBSFX_08_73
	const RBSFX_08_74
	const RBSFX_08_75
	const RBSFX_08_76
	const RBSFX_08_77

	const RBSFX_1f_5e
	const RBSFX_1f_5f
	const RBSFX_1f_60
	const RBSFX_1f_61
	const RBSFX_1f_62
	const RBSFX_1f_63
	const RBSFX_1f_64
	const RBSFX_1f_65
	const RBSFX_1f_66
	const RBSFX_1f_67

	const GSSFX_NOT_VERY_EFFECTIVE
	const GSSFX_DAMAGE
	const GSSFX_SUPER_EFFECTIVE
